### ISSUE TITLE
failure to send manifest after lease obtained

### ISSUE THREAD

**Issue by rsum1** [ovrclk/akash#1068]
I successfully sent a create manifest transaction and obtained a lease.

When sending the manifest I get the following error

```akash provider send-manifest deployment.yml --node $AKASH_NODE --dseq $DSEQ --provider $PROVIDER
panic: could not create directory "": mkdir : no such file or directory

goroutine 1 [running]:
github.com/tendermint/tendermint/config.EnsureRoot(0x0, 0x0)
	github.com/tendermint/tendermint@v0.34.3/config/toml.go:35 +0x305
github.com/cosmos/cosmos-sdk/server.interceptConfigs(0xc00114de60, 0xc001220c00, 0x4, 0xc000d5f608)
	github.com/cosmos/cosmos-sdk@v0.41.0/server/util.go:158 +0x846
github.com/cosmos/cosmos-sdk/server.InterceptConfigsPreRunHandler(0xc001166580, 0x20, 0x7f39ae7a0c28)
	github.com/cosmos/cosmos-sdk@v0.41.0/server/util.go:94 +0x305
github.com/ovrclk/akash/cmd/akash/cmd.NewRootCmd.func1(0xc001166580, 0xc001136cb0, 0x1, 0x7, 0x0, 0x0)
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:82 +0x4f
github.com/tendermint/tendermint/libs/cli.concatCobraCmdFuncs.func1(0xc001166580, 0xc001136cb0, 0x1, 0x7, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.34.3/libs/cli/setup.go:118 +0x7d
github.com/spf13/cobra.(*Command).execute(0xc001166580, 0xc001136c40, 0x7, 0x7, 0xc001166580, 0xc001136c40)
	github.com/spf13/cobra@v1.1.1/command.go:829 +0x587
github.com/spf13/cobra.(*Command).ExecuteC(0xc001087600, 0x28e1231, 0x5, 0xc000f6e210)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.1/command.go:888
github.com/ovrclk/akash/cmd/akash/cmd.Execute(0xc001087600, 0x2ea5080, 0xc00112c100)
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:116 +0x26d
main.main()
	github.com/ovrclk/akash/cmd/akash/main.go:14 +0x2a
```

**Comment by boz** [comment]
This is the first command you used that isn't from `x/*/client/cli` - it's from `provider/cmd`.  it could be that `--home` or `$AKASH_HOME` is not being read correctly from there.

**Comment by rsum1** [comment]
I had misconfigured the `--home` flag. 

Set it to `/.akash` and the send-manifest command worked as intended.
