### ISSUE TITLE
flapping test: tendemint log

### ISSUE THREAD

**Issue by troian** [ovrclk/akash#1132]
```
panic: Log in goroutine after TestBalanceCheckerStartsWithdrawal has completed

goroutine 39 [running]:
testing.(*common).logDepth(0xc0004fe900, 0xc00009d800, 0x52, 0x3)
	/opt/hostedtoolcache/go/1.16.0/x64/src/testing/testing.go:765 +0x5df
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.16.0/x64/src/testing/testing.go:747
testing.(*common).Logf(0xc0004fe900, 0x1bec1a6, 0x2, 0xc000d8f5c0, 0x1, 0x1)
	/opt/hostedtoolcache/go/1.16.0/x64/src/testing/testing.go:793 +0x7e
github.com/ovrclk/akash/testutil.testWriter.Write(0x2069be0, 0xc0004fe900, 0xc000dbc000, 0x52, 0xa5, 0x2be12d7, 0x1, 0x1)
	/home/runner/work/akash/akash/testutil/log.go:20 +0xd2
github.com/tendermint/tendermint/libs/log.tmfmtLogger.Log(0x2015a80, 0xc000c146c0, 0xc000dba480, 0x6, 0x8, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/ovrclk/tendermint@v0.34.8-akash-1/libs/log/tmfmt_logger.go:131 +0xd4f
github.com/go-kit/kit/log.(*context).Log(0xc000d7fe00, 0xc000d92d20, 0x2, 0x2, 0x2, 0x2012ae0)
	/home/runner/go/pkg/mod/github.com/go-kit/kit@v0.10.0/log/log.go:124 +0x202
github.com/tendermint/tendermint/libs/log.(*tmLogger).Debug(0xc000c146e0, 0x1c0495f, 0x15, 0xc000d92d20, 0x2, 0x2)
	/home/runner/go/pkg/mod/github.com/ovrclk/tendermint@v0.34.8-akash-1/libs/log/tm_logger.go:66 +0x187
github.com/ovrclk/akash/provider.(*balanceChecker).doCheck(0xc000c13d50, 0x2052978, 0xc0004bf9c0, 0xc0004da9c0, 0x19cd900, 0x2cca280)
	/home/runner/work/akash/akash/provider/balance_checker.go:54 +0x1b5
github.com/ovrclk/akash/provider.(*balanceChecker).run.func1(0xc000c7a480, 0x2052c00)
	/home/runner/work/akash/akash/provider/balance_checker.go:87 +0x45
github.com/ovrclk/akash/util/runner.Do.func1(0xc000d9e2a0, 0xc000d92c00)
	/home/runner/work/akash/akash/util/runner/runner.go:10 +0x27
created by github.com/ovrclk/akash/util/runner.Do
	/home/runner/work/akash/akash/util/runner/runner.go:9 +0x65
FAIL	github.com/ovrclk/akash/provider	0.664s
```

**Comment by troian** [comment]
fixed by https://github.com/ovrclk/akash/pull/1155
