### ISSUE TITLE
flapping test: cmd/akashd/start_test.go

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#124]
I've seen this happen randomly twice on travis.

```
?   	github.com/ovrclk/akash/cmd/akash/query	[no test files]
Error: open /tmp/Test_Start_Fail543832494/config/genesis.json: no such file or directory
Usage:
  akashd start [flags]
Flags:
  -h, --help   help for start
Global Flags:
  -d, --data string   data directory (default "/home/travis/.akashd")
PASS
panic: Error initializing DB: rename /tmp/Test_Start517339957/data/akash.db/CURRENT.0 /tmp/Test_Start517339957/data/akash.db/CURRENT: no such file or directory
goroutine 23 [running]:
github.com/ovrclk/akash/vendor/github.com/tendermint/tmlibs/db.NewDB(0xc420036dce, 0x5, 0x109d8a9, 0x9, 0xc420036db0, 0x1d, 0x26, 0x0)
	/home/travis/gopath/src/github.com/ovrclk/akash/vendor/github.com/tendermint/tmlibs/db/db.go:33 +0x205
github.com/ovrclk/akash/state.LoadDB(0xc420036db0, 0x26, 0x3, 0xc420036db0, 0x26, 0x13)
	/home/travis/gopath/src/github.com/ovrclk/akash/state/util.go:36 +0x182
github.com/ovrclk/akash/cmd/akashd.doStartCommand(0x12974c0, 0xc42008ce00, 0xc42097af00, 0xc42000d5a0, 0x0, 0x2, 0xc420071bf8, 0xc420071bb0)
	/home/travis/gopath/src/github.com/ovrclk/akash/cmd/akashd/start.go:51 +0x225
github.com/ovrclk/akash/cmd/akashd.testWithContext.func1(0xc42097af00, 0xc42000d5a0, 0x0, 0x2, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ovrclk/akash/cmd/akashd/start_test.go:82 +0x7b
github.com/ovrclk/akash/vendor/github.com/spf13/cobra.(*Command).execute(0xc42097af00, 0xc42000d580, 0x2, 0x2, 0xc42097af00, 0xc42000d580)
	/home/travis/gopath/src/github.com/ovrclk/akash/vendor/github.com/spf13/cobra/command.go:753 +0x4b5
github.com/ovrclk/akash/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42097ac80, 0x412d20, 0xe, 0x2)
	/home/travis/gopath/src/github.com/ovrclk/akash/vendor/github.com/spf13/cobra/command.go:843 +0x4a9
github.com/ovrclk/akash/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42097ac80, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ovrclk/akash/vendor/github.com/spf13/cobra/command.go:791 +0x39
github.com/ovrclk/akash/cmd/akashd.Test_Start.func1(0xc420203020, 0xc42097ac80)
	/home/travis/gopath/src/github.com/ovrclk/akash/cmd/akashd/start_test.go:59 +0x39
created by github.com/ovrclk/akash/cmd/akashd.Test_Start
	/home/travis/gopath/src/github.com/ovrclk/akash/cmd/akashd/start_test.go:58 +0x6ce
FAIL	github.com/ovrclk/akash/cmd/akashd	1.711s
```

**Comment by boz** [comment]
example build [here](https://travis-ci.org/ovrclk/akash/builds/355539842).   always seems to be w/ go 1.10.

**Comment by aastein** [comment]
Is the defer getting called 'too' early? Is that possible? 

https://github.com/ovrclk/akash/blob/master/cmd/akashd/start_test.go#L28

could we move the os.RemoveAll into the selects?

**Comment by aastein** [comment]
My guess is cancel is getting called while the db is initializing. Ill do a PR to increase the wait time.

**Comment by boz** [comment]
It might be related to the db not being closed.  See `cmd/akash/context` changes in #160

**Comment by boz** [comment]
doesn't seem to be a problem anymore.
