### ISSUE TITLE
Following directions fails 100% of the time

### ISSUE THREAD

**Issue by faddat** [ovrclk/akash#1397]
**Is your feature request related to a problem? Please describe.**

```
11:26AM INF indexed block height=967 module=txindex
11:26AM INF minted coins from module account amount=11764116uakt from=mint module=x/bank
11:26AM INF executed block height=968 module=state num_invalid_txs=0 num_valid_txs=1
11:26AM INF commit synced commit=436F6D6D697449447B5B343120313635203435203130362031333620313820323138203133203238203231322031383520313120323435203832203130203133302031373320313735203838203133362032303320313236203130332036362031333720313831203235352033372031373120313736203237203132345D3A3343387D
11:26AM INF committed state app_hash=29A52D6A8812DA0D1CD4B90BF5520A82ADAF5888CB7E674289B5FF25ABB01B7C height=968 module=state num_txs=1
11:26AM INF indexed block height=968 module=txindex
panic: Failed to process committed block (969:681930834E469C09467B56C47D69C6B7674D215DCD4443584D7F6D8E50C63310): wrong Block.Header.AppHash.  Expected 29A52D6A8812DA0D1CD4B90BF5520A82ADAF5888CB7E674289B5FF25ABB01B7C, got 76E781A801DC95404EFF512AAB7B5056EF283E2EA1DFEAC805DAB86E9AE058F3

goroutine 158 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000f76c40, 0x0)
        github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:401 +0x15bf
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:110 +0x8c

```

**resolution**

We need to document a sync process that works.

**Comment by boz** [comment]
Thanks @faddat!  Please make this an issue on https://github.com/ovrclk/docs
