### ISSUE TITLE
state-sync SIGSEGV

### ISSUE THREAD

**Issue by andy108369** [ovrclk/akash#1622]
## state-sync parameters

https://github.com/ovrclk/helm-charts/blob/provider-0.176.0/charts/akash-node/values.yaml#L26-L35

it used to work, but now seem to be breaking.

# akash 0.16.4

## 1st run

```
+ echo 'state-sync is enabled, figure the right trust height & derive its hash'
state-sync is enabled, figure the right trust height & derive its hash
+ SNAP_RPC1=https://akash-rpc.polkachu.com:443
+ SNAP_RPC2=https://akash-rpc.polkachu.com:443
++ curl -s https://akash-rpc.polkachu.com:443/block
++ jq -r .result.block.header.height
+ LATEST_HEIGHT=6357286
+ HEIGHT_OFFSET=2000
+ BLOCK_HEIGHT=6355286
++ curl -s 'https://akash-rpc.polkachu.com:443/block?height=6355286'
++ jq -r .result.block_id.hash
TRUST HEIGHT: 6355286
TRUST HASH: 9AA3F916CCA6D22285C06DB03E5BC961D2D9137E1477C6A22BC15BA9F88C2721
+ TRUST_HASH=9AA3F916CCA6D22285C06DB03E5BC961D2D9137E1477C6A22BC15BA9F88C2721
+ echo 'TRUST HEIGHT: 6355286'
+ echo 'TRUST HASH: 9AA3F916CCA6D22285C06DB03E5BC961D2D9137E1477C6A22BC15BA9F88C2721'
+ export AKASH_STATESYNC_TRUST_HEIGHT=6355286
+ AKASH_STATESYNC_TRUST_HEIGHT=6355286
+ export AKASH_STATESYNC_TRUST_HASH=9AA3F916CCA6D22285C06DB03E5BC961D2D9137E1477C6A22BC15BA9F88C2721
+ AKASH_STATESYNC_TRUST_HASH=9AA3F916CCA6D22285C06DB03E5BC961D2D9137E1477C6A22BC15BA9F88C2721
+ /bin/akash start
Error: failed to initialize database: resource temporarily unavailable
```

## 2nd run

```
+ echo 'state-sync is enabled, figure the right trust height & derive its hash'
state-sync is enabled, figure the right trust height & derive its hash
+ SNAP_RPC1=https://akash-rpc.polkachu.com:443
+ SNAP_RPC2=https://akash-rpc.polkachu.com:443
++ curl -s https://akash-rpc.polkachu.com:443/block
++ jq -r .result.block.header.height
+ LATEST_HEIGHT=6357317
+ HEIGHT_OFFSET=2000
+ BLOCK_HEIGHT=6355317
++ curl -s 'https://akash-rpc.polkachu.com:443/block?height=6355317'
++ jq -r .result.block_id.hash
+ TRUST_HASH=53987FCD9636E2309A576DE1366D4987FF1F66FB043A3AE333E6287F1829D2CD
+ echo 'TRUST HEIGHT: 6355317'
+ echo 'TRUST HASH: 53987FCD9636E2309A576DE1366D4987FF1F66FB043A3AE333E6287F1829D2CD'
+ export AKASH_STATESYNC_TRUST_HEIGHT=6355317
TRUST HEIGHT: 6355317
TRUST HASH: 53987FCD9636E2309A576DE1366D4987FF1F66FB043A3AE333E6287F1829D2CD
+ AKASH_STATESYNC_TRUST_HEIGHT=6355317
+ export AKASH_STATESYNC_TRUST_HASH=53987FCD9636E2309A576DE1366D4987FF1F66FB043A3AE333E6287F1829D2CD
+ AKASH_STATESYNC_TRUST_HASH=53987FCD9636E2309A576DE1366D4987FF1F66FB043A3AE333E6287F1829D2CD
+ /bin/akash start
12:38PM INF starting node with ABCI Tendermint in-process
12:38PM INF Starting multiAppConn service impl=multiAppConn module=proxy
12:38PM INF Starting localClient service connection=query impl=localClient module=abci-client
12:38PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
12:38PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
12:38PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
12:38PM INF Starting EventBus service impl=EventBus module=events
12:38PM INF Starting PubSub service impl=PubSub module=pubsub
12:38PM INF Starting IndexerService service impl=IndexerService module=txindex
12:38PM INF Found local state with non-zero height, skipping state sync
12:38PM INF ABCI Handshake App Info hash=">R�fLS��Y��\x15<6i\b�\\U��R~5C\x12��\x1av\x1e�" height=6349845 module=consensus protocol-version=0 software-version=v0.16.4
12:38PM INF ABCI Replay Blocks appHeight=6349845 module=consensus stateHeight=6357199 storeHeight=6357199
12:38PM INF Applying block height=6349846 module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0xef2189]

goroutine 1 [running]:
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x355c950, 0xc00188ed80}, {0x3587130, 0xc00112a3f0}, 0x0, {0x35a8c58, 0xc003bb4f00}, 0x1f4)
	github.com/tendermint/tendermint@v0.34.19/state/execution.go:270 +0xc9
github.com/tendermint/tendermint/state.ExecCommitBlock({0x3587130, 0xc00112a3f0}, 0x0, {0x355c950, 0xc00188ed80}, {0x35a8c58, 0xc003bb4f00}, 0x261c4a0)
	github.com/tendermint/tendermint@v0.34.19/state/execution.go:537 +0x67
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x0}, {0xc003bb7f37, 0x7}}, {0xc003bb7f60, 0xa}, 0x1, 0x6100cf, {{0xc00272a500, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:471 +0x248
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc003bb7f37, 0x7}}, {0xc003bb7f60, 0xa}, 0x1, 0x6100cf, {{0xc00272a500, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:393 +0x479
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0005c9ff0, {0x35b1f48, 0xc00026c750})
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc003bb7f37, 0x7}}, {0xc003bb7f60, 0xa}, 0x1, 0x6100cf, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00131a780, {0x3528d60, 0xc0016b3e00}, 0xc001701630, {0x34f8700, 0xc0015219c8}, 0x0, 0x0, 0xc001701840, {0x355c950, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x3579348, 0xc000549100}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:272 +0x7e5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0016ad180, {0x4dd1830, 0x0, 0x0})
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0016ad180, {0x4dd1830, 0x0, 0x0})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e39900)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.4.0/command.go:895
github.com/ovrclk/akash/cmd/akash/cmd.Execute(0xc0000001a0)
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:120 +0x1eb
main.main()
	github.com/ovrclk/akash/cmd/akash/main.go:14 +0x1e
```

## 3rd run

```
+ echo 'state-sync is enabled, figure the right trust height & derive its hash'
state-sync is enabled, figure the right trust height & derive its hash
+ SNAP_RPC1=https://akash-rpc.polkachu.com:443
+ SNAP_RPC2=https://akash-rpc.polkachu.com:443
++ curl -s https://akash-rpc.polkachu.com:443/block
++ jq -r .result.block.header.height
+ LATEST_HEIGHT=6357355
+ HEIGHT_OFFSET=2000
+ BLOCK_HEIGHT=6355355
++ curl -s 'https://akash-rpc.polkachu.com:443/block?height=6355355'
++ jq -r .result.block_id.hash
TRUST HEIGHT: 6355355
TRUST HASH: 90D190C108E0C4710E908AA26789DA8A4A3917F38ACB09B2D5B314EE281940BE
+ TRUST_HASH=90D190C108E0C4710E908AA26789DA8A4A3917F38ACB09B2D5B314EE281940BE
+ echo 'TRUST HEIGHT: 6355355'
+ echo 'TRUST HASH: 90D190C108E0C4710E908AA26789DA8A4A3917F38ACB09B2D5B314EE281940BE'
+ export AKASH_STATESYNC_TRUST_HEIGHT=6355355
+ AKASH_STATESYNC_TRUST_HEIGHT=6355355
+ export AKASH_STATESYNC_TRUST_HASH=90D190C108E0C4710E908AA26789DA8A4A3917F38ACB09B2D5B314EE281940BE
+ AKASH_STATESYNC_TRUST_HASH=90D190C108E0C4710E908AA26789DA8A4A3917F38ACB09B2D5B314EE281940BE
+ /bin/akash start
12:42PM INF starting node with ABCI Tendermint in-process
12:42PM INF Starting multiAppConn service impl=multiAppConn module=proxy
12:42PM INF Starting localClient service connection=query impl=localClient module=abci-client
12:42PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
12:42PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
12:42PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
12:42PM INF Starting EventBus service impl=EventBus module=events
12:42PM INF Starting PubSub service impl=PubSub module=pubsub
12:42PM INF Starting IndexerService service impl=IndexerService module=txindex
12:42PM INF Found local state with non-zero height, skipping state sync
12:42PM INF ABCI Handshake App Info hash=">R�fLS��Y��\x15<6i\b�\\U��R~5C\x12��\x1av\x1e�" height=6349845 module=consensus protocol-version=0 software-version=v0.16.4
12:42PM INF ABCI Replay Blocks appHeight=6349845 module=consensus stateHeight=6357199 storeHeight=6357199
12:42PM INF Applying block height=6349846 module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0xef2189]

goroutine 1 [running]:
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x355c950, 0xc000d95ce0}, {0x3587130, 0xc001186400}, 0x0, {0x35a8c58, 0xc002a06d60}, 0x1f4)
	github.com/tendermint/tendermint@v0.34.19/state/execution.go:270 +0xc9
github.com/tendermint/tendermint/state.ExecCommitBlock({0x3587130, 0xc001186400}, 0x0, {0x355c950, 0xc000d95ce0}, {0x35a8c58, 0xc002a06d60}, 0x261c4a0)
	github.com/tendermint/tendermint@v0.34.19/state/execution.go:537 +0x67
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x0}, {0xc002a79f37, 0x7}}, {0xc002a79f60, 0xa}, 0x1, 0x6100cf, {{0xc001b48460, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:471 +0x248
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc002a79f37, 0x7}}, {0xc002a79f60, 0xa}, 0x1, 0x6100cf, {{0xc001b48460, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:393 +0x479
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001813ff0, {0x35b1f48, 0xc000fb6000})
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc002a79f37, 0x7}}, {0xc002a79f60, 0xa}, 0x1, 0x6100cf, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0016ce140, {0x3528d60, 0xc000881cc0}, 0xc00151b7e0, {0x34f8700, 0xc0014584b0}, 0x0, 0x0, 0xc00151b9f0, {0x355c950, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x3579348, 0xc0013232c0}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:272 +0x7e5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00167a000, {0x4dd1830, 0x0, 0x0})
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00167a000, {0x4dd1830, 0x0, 0x0})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc001338780)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.4.0/command.go:895
github.com/ovrclk/akash/cmd/akash/cmd.Execute(0xc0000001a0)
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:120 +0x1eb
main.main()
	github.com/ovrclk/akash/cmd/akash/main.go:14 +0x1e
```

# akash 0.16.4-rc2

## 1st run

```
+ echo 'state-sync is enabled, figure the right trust height & derive its hash'
+ SNAP_RPC1=https://akash-rpc.polkachu.com:443
+ SNAP_RPC2=https://akash-rpc.polkachu.com:443
state-sync is enabled, figure the right trust height & derive its hash
++ curl -s https://akash-rpc.polkachu.com:443/block
++ jq -r .result.block.header.height
+ LATEST_HEIGHT=6357412
+ HEIGHT_OFFSET=2000
+ BLOCK_HEIGHT=6355412
++ curl -s 'https://akash-rpc.polkachu.com:443/block?height=6355412'
++ jq -r .result.block_id.hash
TRUST HEIGHT: 6355412
TRUST HASH: 487CB9CF0C963D6EB5E3B0A1F26268632D3E27B9B80BC7AE63FEF9D6AA5DF469
+ TRUST_HASH=487CB9CF0C963D6EB5E3B0A1F26268632D3E27B9B80BC7AE63FEF9D6AA5DF469
+ echo 'TRUST HEIGHT: 6355412'
+ echo 'TRUST HASH: 487CB9CF0C963D6EB5E3B0A1F26268632D3E27B9B80BC7AE63FEF9D6AA5DF469'
+ export AKASH_STATESYNC_TRUST_HEIGHT=6355412
+ AKASH_STATESYNC_TRUST_HEIGHT=6355412
+ export AKASH_STATESYNC_TRUST_HASH=487CB9CF0C963D6EB5E3B0A1F26268632D3E27B9B80BC7AE63FEF9D6AA5DF469
+ AKASH_STATESYNC_TRUST_HASH=487CB9CF0C963D6EB5E3B0A1F26268632D3E27B9B80BC7AE63FEF9D6AA5DF469
+ /bin/akash start
12:48PM INF starting node with ABCI Tendermint in-process
12:48PM INF Starting multiAppConn service impl=multiAppConn module=proxy
12:48PM INF Starting localClient service connection=query impl=localClient module=abci-client
12:48PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
12:48PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
12:48PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
12:48PM INF Starting EventBus service impl=EventBus module=events
12:48PM INF Starting PubSub service impl=PubSub module=pubsub
12:48PM INF Starting IndexerService service impl=IndexerService module=txindex
12:48PM INF Found local state with non-zero height, skipping state sync
12:48PM INF ABCI Handshake App Info hash=">R�fLS��Y��\x15<6i\b�\\U��R~5C\x12��\x1av\x1e�" height=6349845 module=consensus protocol-version=0 software-version=v0.16.4-rc2
12:48PM INF ABCI Replay Blocks appHeight=6349845 module=consensus stateHeight=6357199 storeHeight=6357199
12:48PM INF Applying block height=6349846 module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0xef2189]

goroutine 1 [running]:
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x3529ed0, 0xc000781aa0}, {0x35545f0, 0xc001080400}, 0x0, {0x3576118, 0xc0029b4bb0}, 0x1f4)
	github.com/tendermint/tendermint@v0.34.19/state/execution.go:270 +0xc9
github.com/tendermint/tendermint/state.ExecCommitBlock({0x35545f0, 0xc001080400}, 0x0, {0x3529ed0, 0xc000781aa0}, {0x3576118, 0xc0029b4bb0}, 0x25f2840)
	github.com/tendermint/tendermint@v0.34.19/state/execution.go:537 +0x67
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x0}, {0xc0029b7f37, 0x7}}, {0xc0029b7f60, 0xa}, 0x1, 0x6100cf, {{0xc001b0a380, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:471 +0x248
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0029b7f37, 0x7}}, {0xc0029b7f60, 0xa}, 0x1, 0x6100cf, {{0xc001b0a380, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:393 +0x479
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001795ff0, {0x357f408, 0xc0001aa000})
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0029b7f37, 0x7}}, {0xc0029b7f60, 0xa}, 0x1, 0x6100cf, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001445180, {0x34f6920, 0xc0006b97c0}, 0xc0006930c0, {0x34c6760, 0xc001227e60}, 0x0, 0x0, 0xc000693300, {0x3529ed0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x35468c8, 0xc001432220}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:272 +0x7e5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00154ef00, {0x4d7ce90, 0x0, 0x0})
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00154ef00, {0x4d7ce90, 0x0, 0x0})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc001249680)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.4.0/command.go:895
github.com/ovrclk/akash/cmd/akash/cmd.Execute(0xc0000001a0)
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:120 +0x1eb
main.main()
	github.com/ovrclk/akash/cmd/akash/main.go:14 +0x1e
```

# akash 0.16.4-rc4

## 1st run

```
state-sync is enabled, figure the right trust height & derive its hash
+ echo 'state-sync is enabled, figure the right trust height & derive its hash'
+ SNAP_RPC1=https://akash-rpc.polkachu.com:443
+ SNAP_RPC2=https://akash-rpc.polkachu.com:443
++ curl -s https://akash-rpc.polkachu.com:443/block
++ jq -r .result.block.header.height
+ LATEST_HEIGHT=6357555
+ HEIGHT_OFFSET=2000
+ BLOCK_HEIGHT=6355555
++ curl -s 'https://akash-rpc.polkachu.com:443/block?height=6355555'
++ jq -r .result.block_id.hash
+ TRUST_HASH=A4D15FB50B0AA7167ED7D9F353D33BA1D92E4076D55EEEBC61BB9187081F4984
+ echo 'TRUST HEIGHT: 6355555'
+ echo 'TRUST HASH: A4D15FB50B0AA7167ED7D9F353D33BA1D92E4076D55EEEBC61BB9187081F4984'
+ export AKASH_STATESYNC_TRUST_HEIGHT=6355555
+ AKASH_STATESYNC_TRUST_HEIGHT=6355555
+ export AKASH_STATESYNC_TRUST_HASH=A4D15FB50B0AA7167ED7D9F353D33BA1D92E4076D55EEEBC61BB9187081F4984
+ AKASH_STATESYNC_TRUST_HASH=A4D15FB50B0AA7167ED7D9F353D33BA1D92E4076D55EEEBC61BB9187081F4984
+ /bin/akash start
TRUST HEIGHT: 6355555
TRUST HASH: A4D15FB50B0AA7167ED7D9F353D33BA1D92E4076D55EEEBC61BB9187081F4984
1:02PM INF starting node with ABCI Tendermint in-process
1:02PM INF Starting multiAppConn service impl=multiAppConn module=proxy
1:02PM INF Starting localClient service connection=query impl=localClient module=abci-client
1:02PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
1:02PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
1:02PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
1:02PM INF Starting EventBus service impl=EventBus module=events
1:02PM INF Starting PubSub service impl=PubSub module=pubsub
1:02PM INF Starting IndexerService service impl=IndexerService module=txindex
1:02PM INF Found local state with non-zero height, skipping state sync
1:02PM INF ABCI Handshake App Info hash=">R�fLS��Y��\x15<6i\b�\\U��R~5C\x12��\x1av\x1e�" height=6349845 module=consensus protocol-version=0 software-version=v0.16.4-rc4
1:02PM INF ABCI Replay Blocks appHeight=6349845 module=consensus stateHeight=6357199 storeHeight=6357199
1:02PM INF Applying block height=6349846 module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0xef2189]

goroutine 1 [running]:
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x355c8f0, 0xc0017b32c0}, {0x35870d0, 0xc000d88440}, 0x0, {0x35a8bf8, 0xc0029e09b0}, 0x1f4)
	github.com/tendermint/tendermint@v0.34.19/state/execution.go:270 +0xc9
github.com/tendermint/tendermint/state.ExecCommitBlock({0x35870d0, 0xc000d88440}, 0x0, {0x355c8f0, 0xc0017b32c0}, {0x35a8bf8, 0xc0029e09b0}, 0x261c4a0)
	github.com/tendermint/tendermint@v0.34.19/state/execution.go:537 +0x67
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x0}, {0xc0029e3f37, 0x7}}, {0xc0029e3f60, 0xa}, 0x1, 0x6100cf, {{0xc001b4e380, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:471 +0x248
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0029e3f37, 0x7}}, {0xc0029e3f60, 0xa}, 0x1, 0x6100cf, {{0xc001b4e380, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:393 +0x479
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001223ff0, {0x35b1ee8, 0xc0017b9380})
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0029e3f37, 0x7}}, {0xc0029e3f60, 0xa}, 0x1, 0x6100cf, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00140b400, {0x3528d00, 0xc001733c20}, 0xc00162f1c0, {0x34f86a0, 0xc0014e9f08}, 0x0, 0x0, 0xc00162f3d0, {0x355c8f0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x35792e8, 0xc0013d8a00}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:272 +0x7e5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00172b400, {0x4dd2830, 0x0, 0x0})
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00172b400, {0x4dd2830, 0x0, 0x0})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc001373b80)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.4.0/command.go:895
github.com/ovrclk/akash/cmd/akash/cmd.Execute(0xc0000001a0)
	github.com/ovrclk/akash/cmd/akash/cmd/root.go:120 +0x1eb
main.main()
	github.com/ovrclk/akash/cmd/akash/main.go:14 +0x1e
```
```
```

**Comment by andy108369** [comment]
Have tried it locally, it looks to be working:

https://asciinema.org/a/503273
https://gist.github.com/andy108369/4e7960df3bd4489599fa693e76d81d05

Then figured that [previously](https://github.com/ovrclk/helm-charts/commit/13b081eb879b20479323fd34fe4f47f80f07355d#diff-653871970405b522a7c8a5fab0780691fa63b33c6b6566a982cd8b3d5ff27f46L26) `~/.akash/data` was `rm -rf`'ed.

The error seen on the 1st run -> `Error: failed to initialize database: resource temporarily unavailable` also indicates the `~/.akash/data` was not clean.

And the pod I've been trying to state-sync, had the local directory [mounted](https://github.com/ovrclk/akash-environments/blob/884da991ef1/tasks/4-akash.yml#L64-L68) as `~/.akash`, hence, combination of the two caused unclean `~/.akash/data`.

Case closed!

cc: @sacreman
