### ISSUE TITLE
Key list throws error with no key

### ISSUE THREAD

**Issue by RiccardoM** [ovrclk/akash#421]
### Issue type
Bug

### Akash version
```
Version:	master                                  
Commit: 	3029981c25c8da24c70a33346c3b49ebb8ba1a50
Date:   	2019-11-12T15:30:07+0100  
```

### Akash token balance
N.A.

### What happened
Running `akash key list` with no previously created key throws the following error:

```
$ akash key list
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/gosuri/uitable/util/strutil.Join(0x27c5cc0, 0x0, 0x0, 0x1843a19, 0x1, 0x0, 0xc0008e1500)
	/home/riccardo/Coding/Go/pkg/mod/github.com/gosuri/uitable@v0.0.2/util/strutil/strutil.go:80 +0x18f
github.com/gosuri/uitable.(*Row).String(0xc0009d6090, 0x0, 0x40e7b8)
	/home/riccardo/Coding/Go/pkg/mod/github.com/gosuri/uitable@v0.0.2/table.go:159 +0x611
github.com/gosuri/uitable.(*Table).String(0xc0008e17e8, 0x0, 0x0)
	/home/riccardo/Coding/Go/pkg/mod/github.com/gosuri/uitable@v0.0.2/table.go:100 +0x3a7
github.com/gosuri/uitable.(*Table).Bytes(...)
	/home/riccardo/Coding/Go/pkg/mod/github.com/gosuri/uitable@v0.0.2/table.go:55
github.com/ovrclk/dsky.(*InteractiveMode).formatSDList(0xc000992280, 0x0, 0x1c07760, 0xc000b4cfc0, 0x1843a19, 0x1, 0x1, 0xc0008e1930, 0xd3382d)
	/home/riccardo/Coding/Go/pkg/mod/github.com/ovrclk/dsky@v0.0.6/iprinter.go:188 +0x6e5
github.com/ovrclk/dsky.(*InteractiveMode).marshalSectionData(0xc000992280, 0x0, 0x1c07760, 0xc000b4cfc0, 0x0, 0x7, 0x7473694c2079654b, 0xa, 0xc0000f2840)
	/home/riccardo/Coding/Go/pkg/mod/github.com/ovrclk/dsky@v0.0.6/iprinter.go:105 +0x7e
github.com/ovrclk/dsky.(*InteractiveMode).MarshalSectionData(0xc000992280, 0x1c07760, 0xc000b4cfc0, 0x4e44e8, 0xc0000f2853, 0x1843a19, 0x1, 0x1)
	/home/riccardo/Coding/Go/pkg/mod/github.com/ovrclk/dsky@v0.0.6/iprinter.go:94 +0x48
github.com/ovrclk/dsky.(*sectionData).Marshal(0xc000b4cfc0, 0x1b9ce20, 0xc000992280, 0x1, 0x0, 0x0, 0xc000aa4000, 0x7fb20f922460)
	/home/riccardo/Coding/Go/pkg/mod/github.com/ovrclk/dsky@v0.0.6/section_data.go:93 +0x8b
github.com/ovrclk/dsky.(*InteractiveMode).Flush(0xc000992280, 0x1843ff6, 0x3)
	/home/riccardo/Coding/Go/pkg/mod/github.com/ovrclk/dsky@v0.0.6/iprinter.go:80 +0x3b8
main.doKeyListCommand(0x1c0d460, 0xc0008ee000, 0xc0004bfb80, 0x27c5cc0, 0x0, 0x0, 0x15, 0x0)
	/home/riccardo/Coding/Go/src/github.com/ovrclk/akash/cmd/akash/key.go:112 +0x415
github.com/ovrclk/akash/cmd/akash/session.RequireKeyManager.func1(0x1c0d460, 0xc0008ee000, 0xc0004bfb80, 0x27c5cc0, 0x0, 0x0, 0xc000b3a000, 0x0)
	/home/riccardo/Coding/Go/src/github.com/ovrclk/akash/cmd/akash/session/session.go:114 +0xaf
github.com/ovrclk/akash/cmd/akash/session.RequireRootDir.func1(0x1c0d460, 0xc0008ee000, 0xc0004bfb80, 0x27c5cc0, 0x0, 0x0, 0x1bed000, 0xc000992280)
	/home/riccardo/Coding/Go/src/github.com/ovrclk/akash/cmd/akash/session/session.go:105 +0xd9
github.com/ovrclk/akash/cmd/akash/session.WithSession.func1.1(0x1bdee40, 0xc00098d980, 0x0, 0x0)
	/home/riccardo/Coding/Go/src/github.com/ovrclk/akash/cmd/akash/session/session.go:67 +0x1d3
github.com/ovrclk/akash/cmd/common.RunForeverWithContext(0x1bdee40, 0xc00098d980, 0xc0008e1d30, 0xd3a036, 0xc00098e880)
	/home/riccardo/Coding/Go/src/github.com/ovrclk/akash/cmd/common/signal.go:35 +0x91
github.com/ovrclk/akash/cmd/common.RunForever(...)
	/home/riccardo/Coding/Go/src/github.com/ovrclk/akash/cmd/common/signal.go:27
github.com/ovrclk/akash/cmd/akash/session.WithSession.func1(0xc0004bfb80, 0x27c5cc0, 0x0, 0x0, 0x0, 0x0)
	/home/riccardo/Coding/Go/src/github.com/ovrclk/akash/cmd/akash/session/session.go:56 +0x99
github.com/spf13/cobra.(*Command).execute(0xc0004bfb80, 0x27c5cc0, 0x0, 0x0, 0xc0004bfb80, 0x27c5cc0)
	/home/riccardo/Coding/Go/pkg/mod/github.com/spf13/cobra@v0.0.6-0.20191014031137-8a4b46fadf75/command.go:829 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004bf400, 0xc0008e1f48, 0x1, 0x1)
	/home/riccardo/Coding/Go/pkg/mod/github.com/spf13/cobra@v0.0.6-0.20191014031137-8a4b46fadf75/command.go:917 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/riccardo/Coding/Go/pkg/mod/github.com/spf13/cobra@v0.0.6-0.20191014031137-8a4b46fadf75/command.go:867
main.main()
	/home/riccardo/Coding/Go/src/github.com/ovrclk/akash/cmd/akash/main.go:26 +0x36c
```

### What did you expect to happen
An empty list to be shown

### How to reproduce it
1. Clean the keys from Akash
2. Run `akash key list` 

### Environment
Linux Ubuntu 19.10

### Anything else we need to know?
N.A.

**Comment by gosuri** [comment]
@RiccardoM what version of Golang did you use to compile?

**Comment by gosuri** [comment]
Upstream fixed with gosuri/uitable#17

**Comment by gosuri** [comment]
This is fixed with, you should have a release soon to with `v0.5.3-rc1`

**Comment by RiccardoM** [comment]
Solved with the following version:

```
Version:	master                                  
Commit: 	73cdf285acf122f14cd1ea68e31ebf08069c8010
Date:   	2019-11-13T11:14:49+0100
```
