### ISSUE TITLE
Runtime panic due to conflicting error codes

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#438]
Running `akash` binary exits with the below error:

```
panic: error with code 2 is already registered: "Invalid request"

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types/errors.Register(0x4d303b9, 0xa, 0xc000000002, 0x4d3c3e1, 0x16, 0xc000beb170)
	/Users/gosuri/code/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.0/types/errors/errors.go:101 +0x389
github.com/ovrclk/akash/x/deployment/types.init()
	/Users/gosuri/code/go/src/github.com/ovrclk/akash/x/deployment/types/errors.go:16 +0x29d
```

**Comment by gosuri** [comment]
Fixed with #439
