### ISSUE TITLE
node sync: invalid evidence (panic)

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#596]
bringing up a fresh node on testnet I'm getting a panic on block 88746:

```
 ./bin/akashd start --home data/akashd abozanich --pruning nothing --unsafe-skip-upgrades 88721 > log.out
^[panic: Failed to process committed block (88746:53525E273128109439DDA8DCD704F702BC70F450503CD0253BCBD169CEA697FA): Invalid evidence: evidence was already committed. Evidence: VoteA: Vote{1:06EB0B0690E1 88720/00/1(Prevote) 000000000000 958C852E7F4B @ 2020-05-15T16:00:01.912956888Z}; VoteB: Vote{1:06EB0B0690E1 88720/00/1(Prevote) D22598A77A73 A08663B0BD4D @ 2020-05-15T15:59:59.73847771Z}

goroutine 25 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00046e820)
	/home/travis/gopath/pkg/mod/github.com/tendermint/tendermint@v0.33.3/blockchain/v0/reactor.go:344 +0x12ea
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/home/travis/gopath/pkg/mod/github.com/tendermint/tendermint@v0.33.3/blockchain/v0/reactor.go:118 +0x84
```

log output:
```
I[2020-05-16|15:15:13.844] Indexed block                                module=txindex height=88744
I[2020-05-16|15:15:13.862] minted 614787uakt from mint module account   module=x/supply 
I[2020-05-16|15:15:13.868] Absent validator akashvalcons1pdmn7n7rjaq36e84yvnqkl5kz25zvpuktjmj0u at height 88745, 23 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.868] Absent validator akashvalcons1r6ejpwlytql0reufcg6fsw3c2nzys6fc0mngrf at height 88745, 23 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.869] Absent validator akashvalcons1x4anm0kyld7trxu4tk9kzjxgul8xlctqgy6fcd at height 88745, 22 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.869] Absent validator akashvalcons1gr04ssh7nlx6uuks3tfwzxmhcyasd9kvyqse24 at height 88745, 23 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.869] Absent validator akashvalcons1gyurmsru47c54ykj672l89n0rjac2de9qcphyx at height 88745, 26 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.870] Absent validator akashvalcons1tywtteuhpjk277xs26zz0lwwug79xmwhj6kf5f at height 88745, 23 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.870] Absent validator akashvalcons1t7nc53lzdydt7n69q54jppctmgzsdwp9tjffha at height 88745, 23 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.870] Absent validator akashvalcons1vgnaqr3r97d6z60lhvemhdvend82m7f0gjxk0h at height 88745, 25 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.870] Absent validator akashvalcons1d273n0qrgpu8cw3xaw2rjq26x8kpnwnra9dr52 at height 88745, 23 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.870] Absent validator akashvalcons10knvrk2hqv2wx4gdralqds3peqpjemcpvljaa3 at height 88745, 33 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.870] Absent validator akashvalcons1smsjsevn89x5lme9x6qa3xzdhk0u7y24z5hc4k at height 88745, 26 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.870] Absent validator akashvalcons1386pp4rq8xm05h2e042ks5jrz6t3yw64gcvu72 at height 88745, 23 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.871] Absent validator akashvalcons1n7ak5dey8wvqgvpqj7zwylc8qtqh28ppyf8j90 at height 88745, 25 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.871] Absent validator akashvalcons15s4aq6nq738uxvndlz9j2k3zauj86rk4ng6kfg at height 88745, 25 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.871] Absent validator akashvalcons148pvex2uqhpnqaaeu62axwd03sjyxk33jhgtjn at height 88745, 24 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.871] Absent validator akashvalcons14vnaq4vtvwe8scdxlu4x7jlrn9emd5zvl8qsqg at height 88745, 25 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.871] Absent validator akashvalcons1hglmurgtdrwwp3p335nfc3qnrmvqlkxpm36a8v at height 88745, 24 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.872] Absent validator akashvalcons1hhpxnuhk9cas94htqjda9gg6gfw0u0efxpvk28 at height 88745, 25 missed, threshold 50 module=x/slashing 
I[2020-05-16|15:15:13.874] processed active leases                      module=main count=0
I[2020-05-16|15:15:13.874] Executed block                               module=state height=88745 validTxs=1 invalidTxs=2
I[2020-05-16|15:15:13.879] Updates to validators                        module=state updates=4C629ED1DC238B71F07C6531290DF18E098C82E6:200895
I[2020-05-16|15:15:13.884] Committed state                              module=state height=88745 txs=3 appHash=B78AC09BF4E02B94A71B77BC8557D15E125CB7388CFADD23626FAB0B723FA816
I[2020-05-16|15:15:13.900] Indexed block                                module=txindex height=88745
```

It continues as normal after restarting the node.

Note: also seem to see severe slowdown as the # of blocks increases.  Quick again after restart.  Will try to reproduce with measurements.

/cc @jackzampolin @anilCSE

**Comment by jackzampolin** [comment]
This looks like a misconfigured evidence module.
