### ISSUE TITLE
Panic when fetching blocks in parallel (fast_sync = true)

### ISSUE THREAD

**Issue by ivan-selchenkov-otg** [ovrclk/akash#969]
### Issue type
Bug

### Akash version
v0.9.0-rc12

### Akash token balance
- name: main
  type: local
  address: akash1dps8d3yt6ngc9fdaxzvarce5wrr7wwd9dkgtr8
  pubkey: akashpub1addwnpepqv59jmnvut6y5hx8p3rhm43cwna5kdytk04zcpev2grfn375jpjx25cn5m4
  mnemonic: ""
  threshold: 0
  pubkeys: []

balances:
- amount: "99948303"
  denom: uakt
pagination:
  next_key: null
  total: "0"

### What happened
Akash app crashed in panic

```
panic: processed height 20643, but expected height 20642 [recovered]
        panic: processed height 20643, but expected height 20642
last events:
0: pcBlockProcessed{20641 peer: 22f70903b004a56a650c9478989230b4a771ee5a}
1: pcBlockProcessed{20640 peer: 6390b433ff3036e7fa6fd9188c9679026fe2bbcc}
2: bcBlockResponse{20644#7302F0EC28DC6E2A1A749A47CF318BF50EAF20A677D965C54B8953C758200385 (size: 925 bytes) from 6390b433ff3036e7fa6fd9188c9679026fe2bbcc at 2020-12-01 06:34:48.884501023 +0000 UTC m=+46.922347947}
3: pcBlockProcessed{20639 peer: 22f70903b004a56a650c9478989230b4a771ee5a}
4: bcBlockResponse{20643#3F59440D4296ABDA24273563F44711CB9522967581696997DC2903731BE292B9 (size: 925 bytes) from 3f843ee34582c4181f00c02643b4b53bb830c3a8 at 2020-12-01 06:34:48.851825943 +0000 UTC m=+46.889672864}
5: bcBlockResponse{20642#32108A062C97B6C7FAB9BC00CCCA52D417BEF8685E3C77EDBB647C248216D700 (size: 925 bytes) from 3f843ee34582c4181f00c02643b4b53bb830c3a8 at 2020-12-01 06:34:48.851738647 +0000 UTC m=+46.889585575}
6: pcBlockProcessed{20638 peer: 6390b433ff3036e7fa6fd9188c9679026fe2bbcc}
7: bcBlockResponse{20641#67F2470CAA03BAE43272F50B4AEE5EFE701B0E1ABE3D73A0CD48E36FA7E12C60 (size: 920 bytes) from 22f70903b004a56a650c9478989230b4a771ee5a at 2020-12-01 06:34:48.781841437 +0000 UTC m=+46.819688352}
8: bcBlockResponse{20639#55AB245FB8F73A12ED3D763CD5CEE934CE8A75C3B269092D284C43F1311CADEE (size: 925 bytes) from 22f70903b004a56a650c9478989230b4a771ee5a at 2020-12-01 06:34:48.781789041 +0000 UTC m=+46.819635948}
9: bcBlockResponse{20640#D512FEBE491E18C891C567824AF4ED2EDEF0F854BAEE7F73578FA49B2CD1E078 (size: 925 bytes) from 6390b433ff3036e7fa6fd9188c9679026fe2bbcc at 2020-12-01 06:34:48.781570762 +0000 UTC m=+46.819417696}
10: pcBlockProcessed{20637 peer: 3f843ee34582c4181f00c02643b4b53bb830c3a8}
11: pcBlockProcessed{20636 peer: 22f70903b004a56a650c9478989230b4a771ee5a}
12: pcBlockProcessed{20635 peer: 22f70903b004a56a650c9478989230b4a771ee5a}
13: bcBlockResponse{20638#0A0D7658908B57FD6DBC5A287E5E61757089E262551D31910286B92B34A99AEB (size: 920 bytes) from 6390b433ff3036e7fa6fd9188c9679026fe2bbcc at 2020-12-01 06:34:48.663657561 +0000 UTC m=+46.701504491}
14: pcBlockProcessed{20634 peer: 3f843ee34582c4181f00c02643b4b53bb830c3a8}
15: pcBlockProcessed{20633 peer: 6390b433ff3036e7fa6fd9188c9679026fe2bbcc}
16: bcBlockResponse{20636#DFDF795F36C0AEEBFB59EB802FC16F71756D6A8891188C72F3C2FE895AB74A55 (size: 925 bytes) from 22f70903b004a56a650c9478989230b4a771ee5a at 2020-12-01 06:34:48.547686274 +0000 UTC m=+46.585533203}
17: bcBlockResponse{20637#FC444E9D582F91F82518B7C967D09C544870F5DE67D7EC277CFA11EC46A40731 (size: 925 bytes) from 3f843ee34582c4181f00c02643b4b53bb830c3a8 at 2020-12-01 06:34:48.54746239 +0000 UTC m=+46.585309327}
18: bcBlockResponse{20634#4AD82FAD3187ACC56CF1948B7D0074C10DFD17F55C1E2D6F57E7E225BED6BB70 (size: 925 bytes) from 3f843ee34582c4181f00c02643b4b53bb830c3a8 at 2020-12-01 06:34:48.547403768 +0000 UTC m=+46.585250698}
19: pcBlockProcessed{20632 peer: 22f70903b004a56a650c9478989230b4a771ee5a}
20: pcBlockProcessed{20631 peer: 6390b433ff3036e7fa6fd9188c9679026fe2bbcc}
21: pcBlockProcessed{20630 peer: 3f843ee34582c4181f00c02643b4b53bb830c3a8}
22: rTryPrunePeer{2020-12-01 06:34:48.462456361 +0000 UTC m=+46.500303268}
23: pcBlockProcessed{20629 peer: 22f70903b004a56a650c9478989230b4a771ee5a}
24: bcBlockResponse{20635#E18578F7617D58A7E3A0912B4489B7674026C1F7A4EB0C057D7339B2F52755C2 (size: 920 bytes) from 22f70903b004a56a650c9478989230b4a771ee5a at 2020-12-01 06:34:48.410427925 +0000 UTC m=+46.448274867}


goroutine 76 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start.func1(0xc001738a80)
        github.com/tendermint/tendermint@v0.34.0-rc6/blockchain/v2/routine.go:77 +0x32e
panic(0x24c74c0, 0xc005ac2f60)
        runtime/panic.go:969 +0x175
github.com/tendermint/tendermint/blockchain/v2.(*scheduler).handleBlockProcessed(0xc001738a10, 0x50a3, 0xc000d546c0, 0x28, 0x401a8e0, 0xd9, 0xc0015dbcf0, 0x518e87)
        github.com/tendermint/tendermint@v0.34.0-rc6/blockchain/v2/scheduler.go:561 +0x257
github.com/tendermint/tendermint/blockchain/v2.(*scheduler).handle(0xc001738a10, 0x2dcf920, 0xc003cf4020, 0x25a8d40, 0x2707b80, 0x10dda00, 0x2dcf920)
        github.com/tendermint/tendermint@v0.34.0-rc6/blockchain/v2/scheduler.go:704 +0xb8
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc001738a80)
        github.com/tendermint/tendermint@v0.34.0-rc6/blockchain/v2/routine.go:94 +0x25f
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).startSync
        github.com/tendermint/tendermint@v0.34.0-rc6/blockchain/v2/reactor.go:151 +0x105
```
### What did you expect to happen
App should keep running

### How to reproduce it
Init node from scratch with fast_sync = true and version = "v2"

### Environment
akash (server): testnet

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

### Anything else we need to know?
Setting fast_sync = false helps to prevent such crashes

**Comment by hydrogen18** [comment]
@ivan-selchenkov-otg is this still an issue?

**Comment by ivan-selchenkov-otg** [comment]
@ivan-selchenkov-otg I faced with the issue a while ago and haven't seen it again since then so I just close the issue
